import { chromium } from "playwright";
const base = process.argv[2], dir = process.argv[3];
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(base, { waitUntil: "networkidle" });
await page.waitForTimeout(1800);
await page.screenshot({ path: `${dir}/brand-hero.png` });
await page.locator("#solutions").scrollIntoViewIfNeeded();
await page.waitForTimeout(900);
await page.screenshot({ path: `${dir}/brand-solutions.png` });
await page.locator("#why-us").scrollIntoViewIfNeeded();
await page.waitForTimeout(900);
await page.screenshot({ path: `${dir}/brand-whyus.png` });
await page.goto(`${base}/services/walk-in-bathtubs`, { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
await page.screenshot({ path: `${dir}/brand-service.png` });
await page.goto(base, { waitUntil: "networkidle" });
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await page.waitForTimeout(1200);
await page.screenshot({ path: `${dir}/brand-footer.png` });
await browser.close();
console.log("done");
